from emojis import EMOJIS

DESTS_INTERNATIONAL = {
    0: ['GRU', 'DXB', 3500.00],
    1:['GRU', 'EZE', 1300.00],
    3:['GRU', 'BKK', 6000.00],
    2:['GRU', 'AEP', 1300.00],
    3:['GRU', 'JFK', 2000.00],
    4:['POA', 'MIA', 2500.00],
    5:['GRU', 'SCL', 950.00],
    6:['POA', 'CUN', 2000.00],
    7:['POA', 'ZRH', 4000.00],
    8:['GRU', 'CDG', 3200.00],
    9:['POA', 'CPT', 6000.00],
    10:['FOR', 'FRA', 3800.00],
    11:['GRU', 'VVI', 950.00],
    12:['GRU', 'MIA', 2000.00],
    13:['GRU', 'ORY', 3500.00],
    14:['IOS', 'LIS', 3500.00],
    15:['IOS', 'MIA', 2500.00],
    16:['GRU', 'FCO', 3200.00],
    17:['GRU', 'LHR', 3000.00],
    18:['GRU', 'LAX', 2200.00],
    19:['GRU', 'LÃS', 2000.00],
    20:['GRU', 'LIS', 3200.00],
    21:['GRU', 'OPO', 3200.00],
    22:['GRU', 'MAD', 2300.00],
    23:['GRU', 'BCN', 2500.00],
    24:['GRU', 'AMS', 2500.00],
    25:['GRU', 'YYZ', 1000.00],
    26:['GRU', 'BRC', 1800.00],
    27:['POA', 'MIA', 2300.00],
    28:['POA', 'CUN', 2000.00],
    29:['POA', 'ZRH', 3700.00],
    30:['POA', 'CPT', 5000.00],
    31:['POA', 'NRT', 5000.00],
    32:['POA', 'CRL', 3500.00],
    33:['POA', 'LIS', 4500.00],
    34:['POA', 'MCO', 2200.00],
    35:['POA', 'LHR', 4300.00],
    36:['POA', 'TLV', 4500.00],
    37:['POA', 'MNL', 9000.00],
    38:['POA', 'DXB', 4000.00],
    39:['POA', 'MEX', 3000.00],
    40:['BSB', 'MCO', 1500.00],
    41:['BSB', 'AUH', 2600.00],
    42:['BSB', 'CDG', 2700.00],
    43:['BSB', 'AEP', 1400.00],
    44:['BSB', 'CUN', 1500.00],
    45:['BSB', 'SCL', 1100.00],
    46:['BSB', 'IPC', 5500.00],
    47:['BSB', 'AMS', 3000.00],
    48:['BSB', 'ZRH', 5000.00],
    49:['BSB', 'MIA', 1200.00],
    50:['BSB', 'CAI', 4500.00],
    51:['BSB', 'MLE', 6000.00],
    52:['FOR', 'TLV', 3200.00],
    53:['FOR', 'DXB', 3200.00],
    54:['FOR', 'LHR', 2500.00],
    55:['FOR', 'LIS', 2500.00],
    56:['FOR', 'CDG', 2300.00],
    57:['FOR', 'EZE', 1500.00],
    58:['FOR', 'JNB', 3500.00],
    59:['FOR', 'YUL', 3000.00],
    60:['FOR', 'SDQ', 2700.00],
}

DESTS_NATIONAL = {
    1:['', '', ],
    2:['', '', ],
    3:['', '', ],
    4:['', '', ],
    5:['', '', ],
    6:['', '', ],
    7:['', '', ],
    8:['', '', ],
    9:['', '', ],
    10:['', '', ],
}

NOMES_SIGLAS = {
    'GRU': f'Guarulhos (Brasil)  {EMOJIS["brazilFlag"]}',
    'DXB': f'Aeroporto Internacinal (Dubai) {EMOJIS["dubaiFlag"]}',
    'EZE': f'Ezeiza International (Argentina) {EMOJIS["argentinaFlag"]}',
    'AEP': f'Aeroparque Jorge (Argentina) {EMOJIS["argentinaFlag"]}',
    'BKK': f'Suvarnabhumi (Bangkok) {EMOJIS["bangkokoFlag"]}',
    'JFK': f'Nova Yorque (EUA) {EMOJIS["unidatedStatesFlag"]}',
    'SCL': f'Santiago (Chile) {EMOJIS["chileFlag"]}',
    'CUN': f'Cancún (México) {EMOJIS["maxicoFlag"]}',
    'MIA': f'Miami (EUA) {EMOJIS["unidatedStatesFlag"]}',
    'POA': f'Porto Alegre (Brasil) {EMOJIS["brazilFlag"]}',
    'FOR': f'Fortaleza (Brasil) {EMOJIS["brazilFlag"]}',
    'IOS': f'Ilhéus Jorge Amado - Bahia (Brasil) {EMOJIS["brazilFlag"]}',
    'ZRH': f'Flughafen Zuerich (Alemanha) {EMOJIS["germanyFlag"]}',
    'CDG': f'Charles de Gaulle - Paris (França) {EMOJIS["franceFlag"]}',
    'CPT': f'Cape Town (África do Sul) {EMOJIS["southAfricaFlag"]}',
    'FRA': f'Frankfurt (Alemanha) {EMOJIS["germanyFlag"]}',
    'VVI': f'Viru Viru (Bolivia) {EMOJIS["boliviaFlag"]}',
    'ORY': f'Orly - Paris (França) {EMOJIS["franceFlag"]}',
    'LIS': f'Lisboa (Portugal) {EMOJIS["portugalFlag"]}',
    'FCO': f'Leonardo da Vinci (Itália) {EMOJIS["italyFlag"]}',
    'LHR': f'Heathrow (Londres - Inglaterra) {EMOJIS["englandFlag"]}',
    'LAX': f'Los Angeles (EUA) {EMOJIS["unidatedStatesFlag"]}',
    'LAS': f'Las Vegas (EUA) {EMOJIS["unidatedStatesFlag"]}',
    'OPO': f'Porto (Portugal) {EMOJIS["portugalFlag"]}',
    'MAD': f'Madrid-Barajas (Espanha) {EMOJIS["spainFlag"]}',
    'BCN': f'Barcelona (Espanha) {EMOJIS["spainFlag"]}',
    'AMS': f'Aeroporto Schiphol (Amsterdam) {EMOJIS["netherlandsFlag"]}',
    'YYZ': f'Pearso Toronto (Canadá) {EMOJIS["canadaFlag"]}',
    'BRC': f'San Carlos de Bariloche (Argentina) {EMOJIS["argentinaFlag"]}',
    'NRT': f'Narita Tokyo (Japão) {EMOJIS["japanFlag"]}',
    'CRL': f'Charleroi Bruxelas (Bélgica) {EMOJIS["belgicaFlag`"]}',
    'MCO': f'Aeroporto Internacional Orlando (EUA) {EMOJIS["unidatedStatesFlag"]}',
    'TLV': f'Ben Gurion (Israel) {EMOJIS["israelFlag"]}',
    'MNL': f'Ninoy Aquino (Filipinas) {EMOJIS["philipinesFlag"]}',
    'MEX': f'Cidade do México Aeroporto Internacional (México) {EMOJIS["maxicoFlag"]}',
    'BSB': f'Brasília Aeroporto Internacional (Brasil) {EMOJIS["brazilFlag"]}',
    'AUH': f'Abu Dhabi (Emirados Árabes Unidos) {EMOJIS["emiratesFlag"]}',
    'IPC': f'Mataveri (Chile) {EMOJIS["chileFlag"]}',
    'CAI': f'Cairo (Egito) {EMOJIS["egyptFlag"]}',
    'MLE': f'Velana (Maldivas) {EMOJIS["maldivesFlag"]}',
    'JNB': f'Johannesburg (África do Sul) {EMOJIS["southAfricaFlag"]}',
    'YUL': f'Montréal-Trudeau (Canadá) {EMOJIS["canadaFlag"]}',
    'SDQ': f'Las Américas (República Dominicana) {EMOJIS["dominicanRepublicFlag"]}',
    '': '',
}