xpaths = {
    'origin_input': '//*[@id="txtInputOrigin_field"]',
    'destination_input': '//*[@id="txtInputDestination_field"]',
    'departure_date': '//*[@id="departureDate"]',
    'return_date': '//*[@id="arrivalDate"]',
    'all_cookies': '//*[@id="cookies-politics-button"]/span',
    'date_departure_input': '//*[@id="departureDate"]',
    'departure_value': '//*[@id="WrapperCardFlight0"]/div/div[2]/div[2]',
    'arrival_time': '//*[@id="WrapperCardFlight0"]/div/div[1]/div[2]/div[1]/div[3]/span[1]',
    'departure_duration': '//*[@id="ContainerFlightInfo0"]/span[2]',
    'flight_time': '//*[@id="WrapperCardFlight0"]/div/div[1]/div[2]/div[1]/div[1]/span[1]',
    'trip_type_departure': '//*[@id="itinerary-modal-0-dialog-open"]/span',
    'company': '//*[@id="WrapperCardFlight0"]/div/div[2]',
    'return_value': '',
    'return_duration': '',
    'returnflight_time': '',
    'return_arrival_time': '',
    'trip_type_return': '',
    'frist_div_departure': '//*[@id="WrapperCardFlight0"]/div',
    'light_departure': '//*[@id="bundle-detail-0-flight-select"]',
    '': '',
}